export const GET_FOOD_ARTICLE = 'GET_FOOD_ARTICLE';
export const GET_FASHION_ARTICLE = 'GET_FASHION_ARTICLE';

export const GET_CHILD_FASHION_ARTICLE = 'GET_CHILD_FASHION_ARTICLE';
export const GET_CHILD_FOOD_ARTICLE = 'GET_CHILD_FOOD_ARTICLE';
